---
- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    operator_user: ubuntu
    prometheus_exporter_ipmitool_enable: no

  roles:
    - role: ansible-prometheus-exporter
